url: https://godspeedyoo.github.io
baseurl: 

# Site settings
title: Joseph Won
email: joseph.won7@gmail.com
description: "A glimpse of me"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6cbee5
  secondary: 1c9bd8  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Joseph Won
  pic: 1
  position: Full Stack Web Developer
  social:
    - title: twitter
      url: http://twitter.com/godspeedyoo
    - title: linkedin
      url: http://linkedin.com/in/josephwon7
    - title: github
      url: http://github.com/godspeedyoo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/godspeedyoo
  - title: google-plus
    url: 
  - title: linkedin
    url: http://linkedin.com/in/josephwon7
  - title: 
    url: 
  - title: github
    url: http://github.com/godspeedyoo

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: San Francisco, CA 94103

# Build settings
markdown: kramdown
permalink: pretty